Rock-n-Block/phenom-frontend

src/components/Header/components/HeaderLinks/index.tsx, src/components/Header/components/HeaderLinks/styles.module.scss, src/components/Header/components/User/User.module.scss, src/containers/Footer/index.tsx, src/styles/fonts.scss, src/styles/index.scss, src/styles/mixins/media.scss
=> fixed fonts

src/pages/Home/components/TopCollections/components/CollectionCard/index.tsx, src/pages/Home/components/Trending/index.tsx, yarn.lock
=> all nft -> all categories

src/components/Header/components/HeaderLinks/index.tsx, src/components/Header/components/HeaderLinks/styles.module.scss, src/components/Header/components/User/User.module.scss, src/components/Header/components/User/index.tsx, src/pages/Home/components/Categories/styles.module.scss, src/pages/Home/components/Trending/components/TitleDropdown/index.tsx
fixes: mobile dropdown explore, all nft
=> fixes: mobile dropdown explore, all nft

src/components/Header/components/HeaderLinks/styles.module.scss
=> explore menu first-child

src/components/Button/styles.module.scss, src/components/DefaultInput/index.tsx, src/pages/Explore/components/Body/components/Filters/components/PriceFilter/index.tsx, src/pages/Explore/components/Body/components/Filters/index.tsx, src/pages/Explore/components/Body/components/Filters/styles.module.scss, src/pages/Explore/components/Body/components/Labels/index.tsx, src/pages/NFTCard/components/Payment/styles.module.scss, src/utils/checkMinMax.ts, src/utils/index.ts, yarn.lock
added min max validation on default input
=> added min max validation on default input

src/components/Checkbox/index.tsx, src/pages/Explore/components/Body/components/Filters/components/MenuFilter/index.tsx, src/pages/Explore/components/Body/components/Filters/components/MenuFilter/styles.module.scss, src/pages/Explore/components/Body/components/Filters/components/index.ts, src/pages/Explore/components/Body/components/Filters/index.tsx, src/pages/Explore/components/Body/components/Labels/Labels.module.scss, src/pages/Explore/components/Body/components/Labels/index.tsx, yarn.lock
=> fix without checkbox bug

src/components/QuantityInput/index.tsx, src/pages/Explore/components/Body/components/Labels/index.tsx, src/pages/NFTCard/components/NameAndLike/styles.module.scss, src/pages/NFTCard/components/OwnersAndCreators/styles.module.scss, src/pages/NFTCard/components/Payment/styles.module.scss, src/pages/NFTCard/components/PropsAndDescr/index.tsx, src/pages/NFTCard/components/PropsAndDescr/styles.module.scss, src/pages/NFTCard/index.tsx, src/pages/NFTCard/styles.module.scss
Nft page: mobile view, Explore: plus minus swap icons, min = max price single label
=> Nft page: mobile view, Explore fixes

src/pages/NFTCard/components/Payment/index.tsx, src/pages/NFTCard/components/Payment/styles.module.scss, src/pages/NFTCard/index.tsx
=> mobile view

src/pages/NFTCard/index.tsx
=> auc and timed_auc fix

src/types/api/Collection.ts, src/types/api/CollectionSlim.ts, src/types/api/HotCollection.ts, src/types/api/TrendingCollection.ts, src/types/api/enums.ts
=> fix for ts Display_theme

src/components/Header/components/User/index.tsx, src/index.tsx, src/store/configureStore.ts
=> persistUser

src/components/Clipboard/index.tsx, src/components/Header/components/HeaderLinks/index.tsx, src/components/Header/components/HeaderLinks/styles.module.scss, src/components/Header/components/Search/styles.module.scss, src/components/Header/components/User/User.module.scss, src/components/Header/components/User/index.tsx, src/components/Header/styles.module.scss, src/containers/GuardRoute/index.tsx, src/containers/Routes/index.tsx, src/containers/index.ts, src/pages/EditProfile/container/mainForm.tsx
1. add [guard route](https://github.com/Rock-n-Block/phenom-frontend/compare/develop...feature/guard-route#diff-f13eb4346671c99fa895ca0e163c56ba8f5f4da0b785dd5a54729cc47e3245d5R1)
2. add [slice](https://github.com/Rock-n-Block/phenom-frontend/compare/develop...feature/guard-route#diff-67ac611eb66618606e66950930ec618cfb4ffb0ac31eaf57f41d5b64aa9d12c1R37) address to `Clipboard` component
3. change adaptive styles of `Header`
=> add guard route

src/components/Header/components/User/User.module.scss, src/components/Header/styles.module.scss, src/components/TextArea/styles.module.scss, src/components/UploadAvatar/styles.module.scss, src/pages/EditProfile/container/mainForm.tsx
edit profile test image fix, textarea font
=> edit profile test image fix, textarea font

src/components/Header/components/User/index.tsx
=> fix return null

src/components/ArtCard/index.tsx, src/components/ArtCard/styles.module.scss, src/pages/Explore/components/Body/components/Filters/index.tsx, src/pages/Explore/components/Body/index.tsx, src/pages/NFTCard/components/Payment/index.tsx, src/pages/NFTCard/index.tsx, src/pages/NFTCard/styles.module.scss, src/store/nfts/reducer.ts, src/store/nfts/sagas/searchCollections.ts, src/store/nfts/sagas/searchNfts.ts, src/types/api/Bid.ts, src/types/api/TokenFull.ts, src/types/store/nfts.ts
=> explore & nft page fixes

src/appConstants/URL.ts, src/hooks/useGetUserAccessForNft.ts, src/pages/Explore/components/Body/index.tsx, src/pages/NFTCard/components/NameAndLike/index.tsx, src/pages/NFTCard/components/Payment/index.tsx, src/pages/NFTCard/index.tsx, src/store/api/nftApiCalls.ts, src/store/nfts/actionTypes.ts, src/store/nfts/actions.ts, src/store/nfts/sagas/index.ts, src/store/nfts/sagas/like.ts, src/store/nfts/sagas/removeFromSale.ts, src/store/nfts/sagas/setOnSale.ts, src/types/requests/index.ts
removeFromSale, changePrice, setOnSale, like actions
=> removeFromSale, changePrice, setOnSale, like actions

src/components/Button/index.tsx, src/components/Loader/index.tsx, src/components/Loader/styles.module.scss, src/pages/CreateNFT/container/mainForm.tsx, src/pages/CreateNFT/container/styles.module.scss
=> mainForm loader fix

src/appConstants/URL.ts, src/components/ArtCard/index.tsx, src/components/ArtCard/styles.module.scss, src/pages/CreateCollection/container/mainForm.tsx, src/pages/CreateNFT/container/index.tsx, src/pages/NFTCard/components/NameAndLike/index.tsx, src/pages/NFTCard/components/Payment/index.tsx, src/pages/NFTCard/components/modals/BurnModal/index.tsx, src/pages/NFTCard/components/modals/BurnModal/styles.module.scss, src/pages/NFTCard/components/modals/SellersModal/index.tsx, src/pages/NFTCard/components/modals/SellersModal/styles.module.scss, src/pages/NFTCard/index.tsx, src/store/api/apiRequestBuilder.ts, src/store/api/nftApiCalls.ts, src/store/nfts/actionTypes.ts, src/store/nfts/actions.ts, src/store/nfts/sagas/bid.ts, src/store/nfts/sagas/buy.ts, src/store/nfts/sagas/createCollection.ts, src/store/nfts/sagas/createToken.ts, src/store/nfts/sagas/endAuction.ts, src/types/requests/index.ts, src/types/store/modals.ts
endAuction. verificateBet, trackTransaction
=> endAuction. verificateBet, trackTransaction

src/appConstants/index.ts, src/components/Header/components/Search/index.tsx, src/pages/Explore/components/Body/index.tsx, src/pages/Explore/components/Body/styles.module.scss, src/pages/Home/components/Trending/index.tsx, src/pages/NFTCard/components/Payment/index.tsx, src/pages/NFTCard/components/Payment/styles.module.scss, src/pages/NFTCard/components/PropsAndDescr/styles.module.scss, src/store/nfts/actionTypes.ts, src/store/nfts/actions.ts, src/store/nfts/reducer.ts, src/store/nfts/sagas/approveNft.ts, src/store/nfts/sagas/index.ts, src/store/nfts/sagas/presearchNfts.ts, src/store/nfts/sagas/searchNfts.ts, src/store/nfts/sagas/setOnAuction.ts, src/store/nfts/sagas/setOnSale.ts, src/types/requests/index.ts, src/types/store/nfts.ts
=> presearch items

src/pages/Home/components/Trending/index.tsx
=> fixed trending swiper

src/appConstants/URL.ts
=> add / on track-transaction

src/components/Modals/modals/SellersModal/styles.module.scss
=> sellersModal avatar

src/components/Modals/modals/QuantityModal/index.tsx, src/components/Modals/modals/TransferModal/index.tsx, src/containers/Footer/index.tsx, src/containers/Footer/styles.module.scss, src/pages/NFTCard/components/Payment/index.tsx, src/pages/NFTCard/components/Payment/styles.module.scss, src/store/api/nftApiCalls.ts, src/types/requests/index.ts
fixed sendAgain approve, added socials
=> fixed sendAgain approve, added socials

src/components/LikeButton/index.tsx, src/pages/Collection/index.tsx, src/pages/Explore/components/Body/components/NFTPreviewer/index.tsx, src/pages/Home/components/Trending/index.tsx, src/pages/NFTCard/components/Payment/index.tsx, src/pages/Profile/Tabs/Preview/index.tsx
=> isAuction bids fix

src/pages/Home/components/TopCollections/index.tsx
top-collections toFIxed floor price
=> top-collections toFIxed floor price

src/components/QuantityInput/styles.module.scss
fix quantityInput +- buttons flex center
=> fix quantityInput +- buttons flex center

src/components/Modals/modals/SendPendingModal/index.tsx, src/components/Modals/modals/TransferModal/index.tsx, src/containers/Modals/index.tsx, src/pages/CreateNFT/container/mainForm.tsx
=> deleted subMessageText

src/components/Modal/index.tsx, src/components/Modals/modals/SellersModal/index.tsx, src/components/Modals/modals/SellersModal/styles.module.scss
=> sellersModals layout fixes

src/pages/NFTCard/components/Payment/index.tsx, src/store/api/nftApiCalls.ts, src/store/nfts/sagas/approve.ts, src/store/nfts/sagas/buy.ts, src/types/requests/index.ts
=> fixed tokenAmount

src/pages/Home/components/Banner/index.tsx, src/pages/Home/components/Banner/styles.module.scss, src/pages/Home/components/Trending/components/TitleDropdown/styles.module.scss, src/styles/helpers.scss
move trending dropfown body, metaverse under background
=> move trending dropfown body, metaverse under background

src/pages/Home/components/Categories/index.tsx
=> categories font-size

src/context/WalletConnect/index.tsx, src/store/nfts/sagas/approve.ts, src/store/nfts/sagas/bid.ts
=> bid in progress

src/styles/helpers.scss
=> home page banner z-index

src/pages/NFTCard/components/Payment/index.tsx, src/store/nfts/sagas/createToken.ts
=> fix usd*amount price

src/pages/Home/components/TopCollections/components/CollectionCard/index.tsx
=> floorPrice NFTCard collection

src/components/Header/components/Search/styles.module.scss, src/components/NFTList/index.tsx, src/components/NFTList/styles.module.scss
search input, loading Profile page
=> search input, loading Profile page

src/components/NFTList/index.tsx, src/pages/Explore/components/Body/components/NFTPreviewer/index.tsx, src/pages/Profile/Tabs/Preview/index.tsx
=> loader && skeleteons
